platform :macos, '10.14'
source 'https://github.com/Lausbert/PodSpecsArchitekkt.git'

use_frameworks!
target 'SKArchitekkt_Example' do
  pod 'SKArchitekkt', :path => '../'

  target 'UITests' do
    inherit! :search_paths

  end
end
